branches: {only: [master, test]}
environment:
  matrix:
    - TOXENV: py37-pipmaster
    - TOXENV: py37-pip181
    - TOXENV: py37-pip10
    - TOXENV: py36-pipmaster
    - TOXENV: py36-pip180
    - TOXENV: py36-pip10
    - TOXENV: py36-pip9
    - TOXENV: py35-pip9
    - TOXENV: py34-pip9
    - TOXENV: py34-pip8
    - TOXENV: py27-pip181
    - TOXENV: py27-pip10
    - TOXENV: py27-pip9
    - TOXENV: py27-pip8
install:
  - python -m pip install -U pip setuptools wheel
  - pip install codecov
  - pip install tox==3.4.0
build_script:
  - python setup.py bdist_wheel
test_script:
  - 'FOR %%w IN ("dist\*.whl") DO tox -v --installpkg "%%w"'
cache:
  - '%LocalAppData%\pip\cache'
after_test:
  - codecov
